// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ClgRHSEYR4yJjW9tHA0nFHoRlkL8Y9g',
    appId: '1:717661228604:web:43aea3c60362bea82fbd39',
    messagingSenderId: '717661228604',
    projectId: 'delivery-box-dc699',
    authDomain: 'delivery-box-dc699.firebaseapp.com',
    databaseURL: 'https://delivery-box-dc699-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-box-dc699.firebasestorage.app',
    measurementId: 'G-SJHNPXTTN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJZwW37cYyk3bKzTf2sOWhaO0QqJjfmKw',
    appId: '1:717661228604:android:5d8b742a3e974c332fbd39',
    messagingSenderId: '717661228604',
    projectId: 'delivery-box-dc699',
    databaseURL: 'https://delivery-box-dc699-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-box-dc699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo0-jM5klJ6aQNzaE14Rcu0KJ2VdVOWpw',
    appId: '1:717661228604:ios:29849c077243a7172fbd39',
    messagingSenderId: '717661228604',
    projectId: 'delivery-box-dc699',
    databaseURL: 'https://delivery-box-dc699-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-box-dc699.firebasestorage.app',
    iosBundleId: 'com.pnj2k7.smartdeliverybox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo0-jM5klJ6aQNzaE14Rcu0KJ2VdVOWpw',
    appId: '1:717661228604:ios:a581015a10b4fd492fbd39',
    messagingSenderId: '717661228604',
    projectId: 'delivery-box-dc699',
    databaseURL: 'https://delivery-box-dc699-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-box-dc699.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeliveryBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ClgRHSEYR4yJjW9tHA0nFHoRlkL8Y9g',
    appId: '1:717661228604:web:a0b5a6aece57de772fbd39',
    messagingSenderId: '717661228604',
    projectId: 'delivery-box-dc699',
    authDomain: 'delivery-box-dc699.firebaseapp.com',
    databaseURL: 'https://delivery-box-dc699-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-box-dc699.firebasestorage.app',
    measurementId: 'G-JECVM8SVLP',
  );
}
